hash-format = "sha256"

[[files]]
file = "config/fwaystones/config.json5"
hash = "0e9373456069882a44fbbd36e26a0bd66cf140dbe1d1cb152d3a6e0fe38463cd"

[[files]]
file = "config/iris.properties"
hash = "e9552a26229903507a9c4a1690206a9e77a0c9e38cfdefaebfe5ceafd0b35a9d"

[[files]]
file = "config/modmenu.json"
hash = "4e044664c7c51c50816f760f3659338bd944115e8609ca13d8232d14d23e997a"

[[files]]
file = "config/smoothswapping.json"
hash = "655a36e674d613ff008e833880a6902c2c13c85c84f838fdd3c3a2ce04bda12a"

[[files]]
file = "config/sounds.ui.config.json"
hash = "f708f9d631e4fb83e903b4402fa4c9ce1d96ad0c535674929c1e1589a12f1759"

[[files]]
file = "config/styled-nicknames.json"
hash = "f4c69845ef4fcbc6a4ae4347491d32f6eb494a0184457328533fca5aea9f3b87"

[[files]]
file = "config/universal-graves/config.json"
hash = "f40908e78562b3dd464fff1391fee5ba680fe51fbff557f5cbf82e39e0a53d03"

[[files]]
file = "kubejs/README.txt"
hash = "35e3c6ff70236e1bb6bf1f12fdbabc9a3e9941cb4e3c3567b5c697d34b210b36"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/buckets.json"
hash = "9e0b73175244288cad01acf7f0da3fb6b8656598e29d03a7d58a69366537a087"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/explosives.json"
hash = "77b0055742519d3fdd88e07a97d9210b769a5a52118bbf6c02a62501401a0323"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/food.json"
hash = "9299c149fc7519df24394f81f97a0eda3e033654ebb6145205ba53fef506b301"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/misc_tools.json"
hash = "2ea13f0d5481a590fdbe5c9768b0fa8590cecd5f4f9b43b9e63f892edff96b2a"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/tools.json"
hash = "6a1929de57b842acae8a5d1bef3ba18c450824e6aa5afd0c04f567dfc94b8c70"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/weapons.json"
hash = "437911bf3a2fefa7e456112bd0d003354dbcefaefa05d87438a5ffa5a0871cac"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_conveyor.json"
hash = "dc50c73abd2bf3b428fcb80921e59ccc008240c676dc62e520c0d895b493844f"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_fluid.json"
hash = "1b763e6c1a2a0b2bda0f051e49a88b608893d34fbb4829c28ff54f05749b611e"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_gears.json"
hash = "631a2f9c31e27c620b4b52f2bc2cb676c5520bebb9bae129461eae924be14932"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_generator.json"
hash = "545ecad6e02b3fc9fd323801f4737dab499ed343b2707e5a8d8160a362cf5dc1"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_mover.json"
hash = "5fe0a354b71f7efa04a05658a96e83715b2cba08ca0fa836585b9a96e6df0a97"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_seats.json"
hash = "318aee8c2385bd801d46a81b8eff12e341e7f6166cab263d1f0ef8b05f612b78"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_tasks.json"
hash = "a45e9880668cf7cf56733f995cbd4e19612530c403e9846b5363c4aa70bc5f58"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_trains.json"
hash = "83eb967ca5ea47b0ecb8dfa7b90c0ff7684fa0eef5279c02a17fb99e2af6785e"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_valves.json"
hash = "c7ac7548135af19ec93b7f1568efcbd8057de502cd0a188c35815628dc4136bd"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_secondary/create_windmill.json"
hash = "e8009a345a28bf86c19a586d5976ceda22557a4d4a7c944103648b569db45021"

[[files]]
file = "kubejs/assets/kubejs/textures/item/computer_chip.png"
hash = "4fd1442654bb372c9ae8e17207008bf19130188009e1c2eaec90ab440784adf8"

[[files]]
file = "kubejs/client_scripts/script.js"
hash = "a15ab0cd467ca9734360ed6609346a3b7161f1a2f46cf0f126c58d18f5361ac9"

[[files]]
file = "kubejs/config/client.properties"
hash = "862aaf6aed16480b2579c7fcc49c66c5c4181c6e099d7dfba726ab9ede7ce2a6"

[[files]]
file = "kubejs/config/common.properties"
hash = "5a4543e460897775a18928c73fd8eed1d27047bbef256cc55d4e396b4febe119"

[[files]]
file = "kubejs/server_scripts/computer_chip.js"
hash = "15190a90f2cf46d15b9888b9f15c1d31916869e20a8b48d0cbb8abaca344e28d"

[[files]]
file = "kubejs/server_scripts/script.js"
hash = "a15ab0cd467ca9734360ed6609346a3b7161f1a2f46cf0f126c58d18f5361ac9"

[[files]]
file = "kubejs/startup_scripts/computer_chip.js"
hash = "859616468f40d1173d7b45453f709a1c8a74a34b0e8c55fccae33a50bf4b11cf"

[[files]]
file = "kubejs/startup_scripts/script.js"
hash = "a15ab0cd467ca9734360ed6609346a3b7161f1a2f46cf0f126c58d18f5361ac9"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "37c4d172d079936ab4348c00f27cab0ef062ffec586566e989563c4eed9ba6b3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a243675bc757485925b293932ee289b9fbcfb3b75bd3ba74eca7603f191cedad"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "ead86ab1bacf74c7ad2d28c11157c2982fab4d15d2c25158e77b7491eff3d983"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "4531db2542b54aeea35ae6ab95da5a50667c0d53644ae5c43fb5a94b1237e9dd"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "6f3c94c24b727270e851fb923b5347d44b5a401f56c11c8e00beffe099986968"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7721e78d990cc15c02f1a03cd6d7652ea995b271a3d19a6ae44829b4c69acbf0"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "bcaceffce281382be8a9a6fe5215f79e3edf5b5968eac57bd62162172b4d7616"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "d94da74c5f4dce9b7b6586f04b3bfe99ff2b2b5298258b8ab9b111c1c126bb67"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "fd15a165cf8782b21ea9ce958468dbb4bee1fc092fd3d83f901631e075eced75"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a89dfcc985612a275975d4823a24fc3dceb244bacb2e8f81bd459283bf1b9fe9"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "524505b468ca28db75538936dbaea65fc42d13d07e821ed8c054fe7146044535"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "f292a7607f682264fa89245e1851c21bc654fedebf3c9b0d60decc275e512549"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d7d7af9930bd78b659aa22d30614cbe8018afa3a854a52fdd899cda619f7a0b1"
metafile = true

[[files]]
file = "mods/create-fabric-sodium-fix.pw.toml"
hash = "738234a75b69eadde29b6ebda5f0be28a3ac7f583d31f9a9a62febd4e784c3b7"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "4175b5ae65bfff65d1f04f908aa1aa894c9e7131d10383edb874542866276272"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b8270928d44781b9e59982d376bb3cc0d24089ceebef3c79d3e1e881ba7ece60"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33f865a014f3acf2c1f2c452bfe7ba1a864acad178322a6eab3759c7e63c9654"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "06859e85abd86899e44b38c090d53f5804550aca2a23924fbb6bb1867d0b859a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f6f8827bc39d892a56351a6cecd39176addebb2ebf1c608b761b0d1985080b05"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "bd278a821fa158a7ffedb511c84e5bc0887192ceae21f9038b30357edd64a9e9"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "dc4a6ad558baacff8619bcb127784bfa27eb6ca4c177eae12d86b833eca80694"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "129bb8b135edc60038f021b693f5b88a0067b722f326e0d6067112243774289b"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
hash = "8afe478f0e3b3d0609ea7efac63d9312302ab8261fffc964b9ad5d7b3d9eafc6"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "6397162c78c64d7e9130223c3a4094ea680df41a4d12f11a2c7fbfb6a73da202"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c4afda1d505225ad18e689ded06f0ed170dec2ea5e6c9621277b565d0fc338b8"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "8a70f97536490d193879303f378d5fb1d843ba5bf98f59d7369ddfe761642285"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "0c5e71addef34c8dcd1c81dfc2ad851a3e274b9d8d3a7d388e1113d4139bf8d8"
metafile = true

[[files]]
file = "mods/individual-keep-inventory.pw.toml"
hash = "f7f8e69b5930cfe0df4648eee9fefc2f5c94b3c911fb107d9eff59835d3dad4b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "41a3116f5642d40ed54efda3f863373fa4d3c0c3a24a447a38c8a106e9fbb079"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "272364f96e69b8ae95f7074e327bad21b52a73a01610f02f617a1e69b4b781e2"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "8a658c051f89ffe246626c6405feea7b62bab42e4780f994864f898f38a4662f"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "b9381641862e1f83025aa6ba94da61a510dc4c7f7bbacf9bf5222741ced5bd30"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "62fe935015220fde5fa84833905a0a7704821e7154f1ef733cb8a2beb8371304"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/log-ip-remover.pw.toml"
hash = "1a1a71979f82e0b35e48c2d54803ea732341dc45a9494123154c7eac55075ff3"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "8f8650f906d35b4c6d7fb0040ae55fcfcfe51788d991bde0ea8415b66acabf29"
metafile = true

[[files]]
file = "mods/map-atlases.pw.toml"
hash = "6bdcc4657a59339b1849d1a4757aa551394fe6effc3b602b46f4ddc6933bea85"
metafile = true

[[files]]
file = "mods/mcr_blahaj.pw.toml"
hash = "9c72d51f02d4c31dcca106732731d33cdee50fdb86df8c5111a329c64923308a"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "aa1cebfcacb1eb5019bd5ae27591a4201732afd49b8ac46f8fe2dfd059dc4b75"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6063147a48c044764c85e6692513c95fc6b7f6c02f17318ad350a63f386c492d"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "868072899da07c08348ad8ce6361dbeaa6df7f34379c6540791ee5b39726d7db"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "051b1bee4a7fd8f2a55753fe95eda061e0f2a724c5b8ad38d2ca3619c88f2fae"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "a2a38850af0076bcfb2c34327f59626d73a87876d03c4039092babfc673428c6"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "28b3e0806647eb166e942cf6552993bb6d666949c53f0d51927bdfb063cb6cc4"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "1bdc2b4d59ee6805bcd05fb4a68782c2a020270a7da21531b245fd03b5ba2426"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "950c4d55de6f6b1480d248e48f7898bcb7120eb887ddd04d4ca9f9ff384345fa"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8ac138bcb2e461b627f0dd7c681a07ac8396e65f8211c37e639acb4fed86754b"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "f3dbbcc93a34c8ba38b2e5a1ab3d5e898099d420ded6bd14ac01e0a7386b3b9a"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "842f27fb68572fa7482ef90f8d1ffed7d3ecc698af5184f65d89458c574694f7"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0cff114a6675b084da449802c5b18b149450904a3362096a97a39643a21d9222"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "89fc4d8fa43ced76ba5452eef196d5986d831ba828921cc133e4fc6139a123f0"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "1a89905c3f470709eed88830d619115f588033e82648149408b1aff960c519d3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9a927c3e0830ba32e1b8a2e543597781724462595b8cce58f676962b442bb52b"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "744dad7997bff08cfd74dfc612d984455c86c6e4fe9351f316d115c6bb99e84b"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
hash = "274b84b0e258d26e57d647506d0d1995da1fd82cecbedbe98caeedd45faa4d23"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "dcd13a0bd0f57a082ad983c3d285f0dafc4e9e4b6af9b1008e15c57428154d5a"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "dbbeb7a8f32fdbe0d5e44a8c7671ed2297ee8d12d4610500ac54742e70b4fb53"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "b2e02d1210f025b905299bfc88f895058640158343322641aca2c4875622c992"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "fb567e276e5ae628a1fa843b264dc01532c86942a69e5d2352be44a1be63674b"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "ed77ef0ba487dea1aa253926993b0a4b5bd03a4997d7ab42ea0ac7246040a03e"
metafile = true
