hash-format = "sha256"

[[files]]
file = "config/bobby.conf"
hash = "32a51f87b98c4bf0b5e2b996e14fa14c2ee4d6d04ad3b5a939ad00dd25c6649b"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "7849b2952a69e67303d1afeef3a5504f3bf6ee008ebce28248b1af7d3a33750b"

[[files]]
file = "config/emojiful.json"
hash = "93ed3e7df540ee71fe099bbafe36e10d51adb47f0dd39236e78371cba13f2b40"

[[files]]
file = "config/fwaystones/config.json5"
hash = "f3eab60089ca26ff4a5214126f6435965cd756511380ba7953ca992f34b32a4f"

[[files]]
file = "config/iris.properties"
hash = "e9552a26229903507a9c4a1690206a9e77a0c9e38cfdefaebfe5ceafd0b35a9d"

[[files]]
file = "config/modmenu.json"
hash = "9a4167c3cfc6e5b9f3da789d949772f6ce4ec9e071e63b490bd01ce9da652427"

[[files]]
file = "config/smoothswapping.json"
hash = "3c4d5c4265caf92be8ad31c6d2fc5bfc89bbd442dad461f5f95563b6c0ba4fb3"

[[files]]
file = "config/sounds.ui.config.json"
hash = "6aac3f72fc49533e742020558a96b00ba474e1a2765b43779121b7cec7e2489a"

[[files]]
file = "config/styled-nicknames.json"
hash = "fb04f0502cc418c19e745d3fef081c2315535ec1f034c129852a448340b0f466"

[[files]]
file = "config/timeoutout.json"
hash = "3966f424909049ba418dbb23be0f18efe19bb1bb33091cf15145ab8145c60b9a"

[[files]]
file = "config/universal-graves/config.json"
hash = "4c5276ee0fb6d3aaef83406b5b73dfdcb291959edf3f82c4a8ba2e989daa0c54"

[[files]]
file = "kubejs/README.txt"
hash = "35e3c6ff70236e1bb6bf1f12fdbabc9a3e9941cb4e3c3567b5c697d34b210b36"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/buckets.json"
hash = "e52f1905121903702d9cd3e811e3638212aae3a9da96f77fad7a98b4155a150b"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/explosives.json"
hash = "418cf1dc93fa1314228f5ea62236855790b61f894912706a82b55916bc76b9de"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/food.json"
hash = "e00b490d15ba194f2567b01a52a567a07e8d4ccb78c17a03a24088e54e72b242"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/misc_tools.json"
hash = "3794633be16509131fd9e207309a2648bc9a85e1c62aa4fe3a6fe3738b7748cd"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/tools.json"
hash = "00a4e653fb908fb29096e30af9badb9158f03728b58589a7c50bcab2e50cb6a2"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/list/weapons.json"
hash = "d8c89a26231844e029a88095cf67de05f511cdfe9a486781a738daf5d48a6fb4"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_conveyor.json"
hash = "090dc73ac524f8e285cd8028642551455b1deba92f084182cc816935e073720b"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_fluid.json"
hash = "89d0e39d9a84dbd381c51e23de9c8480cef2a4184e912f9318b66046da43befe"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_gears.json"
hash = "ce44f216be4e6804875eb7cf172fd6264474d47aaab08c41e992e359b2e8ac8a"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_generator.json"
hash = "639ed7f1270311577c8f7fc37a4571559a291f73c1d39ca260504609004ae02c"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_mover.json"
hash = "04dd073917b7588b1ba177be6a21e8024bfc04534797aa95e2181afe31cb7840"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_seats.json"
hash = "3be17c73a39b30cc4a01a3d300c1fcc6920a07ca19eb1f3ebc6d4b20b4d67dcf"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_tasks.json"
hash = "7159214eb94aeaa73b20333f80e5e4f6258a5bb50e338f316ff4a0513fc05759"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_trains.json"
hash = "1218d1295a37cae9622f726a4bd731626a241f897b619e875bb90a952ddd905b"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_primary/create_valves.json"
hash = "5055a7ead49e5580ddcb94b8e45c708d70d29a6233942a15ddc0a87cd6d204b2"

[[files]]
file = "kubejs/assets/itemswapper/itemgroups/wheel_secondary/create_windmill.json"
hash = "e2f9e118f2e3494539a62001b3418c7619ead0df820024ae48d8101b90c7b129"

[[files]]
file = "kubejs/assets/kubejs/textures/item/computer_chip.png"
hash = "4fd1442654bb372c9ae8e17207008bf19130188009e1c2eaec90ab440784adf8"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_0.png"
hash = "74dd6a8230271426a82098ff711f270b2d3445153565049bb4bdf1cefdf4af72"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_1.png"
hash = "7e558ae04aa529455772fc56c50ac48cd8a16194eafb1d213d9e82fc91a9339d"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_2.png"
hash = "3af5f7d6d1072d2d78e3ec66123df5362ee9f00afec74dbe37f4cd32c529a523"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_3.png"
hash = "90941c836f3b5cb0b55922710ba3bc779b7f04bc24662689962379d0b48530ef"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_4.png"
hash = "615f78381804f0b29b18a9fc677e72572db84b5afa12ae2ae58562827f63c9ba"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_5.png"
hash = "34ec120ea0043a6fcbc21d008ee82982107d24e7f8a2ad3f515b31bcacceffe6"

[[files]]
file = "kubejs/client_scripts/script.js"
hash = "a15ab0cd467ca9734360ed6609346a3b7161f1a2f46cf0f126c58d18f5361ac9"

[[files]]
file = "kubejs/config/client.properties"
hash = "862aaf6aed16480b2579c7fcc49c66c5c4181c6e099d7dfba726ab9ede7ce2a6"

[[files]]
file = "kubejs/config/common.properties"
hash = "5a4543e460897775a18928c73fd8eed1d27047bbef256cc55d4e396b4febe119"

[[files]]
file = "kubejs/server_scripts/computer_chip.js"
hash = "6157f9c4472e6b8daf6f0cb53c323bc981b04af87ff8f77c2f0e9da7bfec4d85"

[[files]]
file = "kubejs/server_scripts/create_casing.js"
hash = "709a8b944b013fa05d8599cfc92fa82858d7e6ff6eb83494fb61099d18742420"

[[files]]
file = "kubejs/server_scripts/minecart.js"
hash = "83d239424557c8e71dfb4ad511e6da249e58e133db7e6c31dac736ac38c1db5e"

[[files]]
file = "kubejs/server_scripts/script.js"
hash = "a15ab0cd467ca9734360ed6609346a3b7161f1a2f46cf0f126c58d18f5361ac9"

[[files]]
file = "kubejs/startup_scripts/computer_chip.js"
hash = "0540bf1f58852cb36e31f5eb97cfb589b1e31053731ad223e58e6898e8fc564a"

[[files]]
file = "kubejs/startup_scripts/script.js"
hash = "a15ab0cd467ca9734360ed6609346a3b7161f1a2f46cf0f126c58d18f5361ac9"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ea6566d896b21e1063193bf84c9880a3da54fbd5e41633982f01ec254bf3b13c"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "52f857d4d493de3f9c95258269268e55f0dd5e201f7f58fcd0637b90815128a9"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "59e8aff7f543265d0258406b964a70300ddf6d8968cd2c339fb4d41a593e01d6"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "6938a873b5ebf20c3132546e789ff2f27da6776e2f661005e781f692868ac6d1"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "ac1d61be47d7db220294764cd4d98e9704b3357ef95adce4c4ea1990b51e8771"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "8913f5168902d8e04e2d3f84736cbbea20f84d204db89ea88ef7c96a950a9505"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "9aa13c42840fd8f738b15c1bf4268ff6d7cc5597448fab1b8a370504cfe3980e"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7aaa8842b23cda2a86886d010989c851f7e8e36a25dc3b012050c641a2e55b7a"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "f2d930b8fd2e02e5f46df2b0b406598945795ca6d3e7acaac24f3016eeac968e"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "29c2464cd9351b7c17988991216cb5203fc2abb3b6a56c4ec653a057ff5959d6"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "14f58b917d0b4385c287f40647fc5e29eb79d6dd16babe53b3ed1c83f4397665"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7ac9e4a5bf35fbfd59aa567f8f8c3c9d78fa07656f107b3434dab285bc74548f"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "077201baa949977a84532ccd00cd662de9a21a5c296476f20753093eedd6e672"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "481ccfad4ea75749c28cb466aafafc170f57be4ddc9c97154fb1451a9ca1db61"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "50f83620ce68b40f152afaa431e28fbab5993b3af4d66839a082f92dfe7adfcb"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
hash = "e0bd919e1de97e4da82e980cf03d90460d5699fb820483de48afe256c145ad35"
metafile = true

[[files]]
file = "mods/create-fabric-sodium-fix.pw.toml"
hash = "59c126c23f79a42080b61334db4c2ccd17b5543a691be5c6970e6a859025dbf4"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "ab4e5eeaf501de9a7a67fc92c87ed0f65daf854eb72273260fe31f10a0e2cf7b"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "36a96fbc964cac8b94074c8d2880f004eb3b01e9525f6cbb4635b1169c5103f1"
metafile = true

[[files]]
file = "mods/createfabricreibugfix.pw.toml"
hash = "3946fff669343151e9f8a7a1000f741037d2552cb6ca93c26b9fed86b1fba90d"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "6f060b8105db55cde49b08ddacc67971477a0544c93c363d0cd631d95cd65dde"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "fab8b1c7a0dc893757f84d978bc4edfd54ffed8b744c2f361d44c050c5173d8b"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "2293302c8617c5226e20f9d6354ee93e90c9254ab70fe4035e00d7d03bfac707"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "839eb2703122aea0bb74cb4f4336eb91248a53a97fa15dfd6a0d96f88d776d23"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d2882cba9089e7f949af2bacc7ff4c2630f2e2fd8272c4ddfd61d94924a52a3f"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "16ba22642af2c6b5e51f5ede26507436d522c2389c6945d6e5d3563bd6fe26cf"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "045ba6424e9cc0a572f841fd36f7cb76651bcd72edbe0d682f612a25dc350f44"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f0f6fc2400c76c472c86a62bce438d8f92d4dc081bb5f314f6b25c206fd0ade1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "db8a136c0fa2bb2f8a7fda0eb8bf0b3f0a8f7b0882ed7ff94867982e6c137b1f"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "cd2b5a6e6336b0e1771b0b45b164382c29f19321f8c4d9fb3937e21035587932"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d96ab4df0850d8f6f42c8fc4ddebfa004606d3d2d355c8b0c7f91982d0a66abc"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "3d937955622404d446aa06eb3cb7393090a8b06e486f65cf2a98a817e3a41e11"
metafile = true

[[files]]
file = "mods/framework-fabric.pw.toml"
hash = "2888572281820401e214561ae4f77c911430170704e344da901bfa8317e53bf9"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
hash = "109af9d68aeb998f5f6fa47241e6dd34f9d6fdfaf633c8683333df34aa1b596a"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "343dc30328f66750b2d1911c64ea2c022b0b5c13736e2be8be917b0759c5fd71"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c7e55cb013917aba16d88ad9d19d5430602b80c18fc9bc1744e8a8de0b8a4f1c"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "2bc1e9ea05ec903ba6cd2b2d153f8fa15476c0d591a41b165a65c5724fdbc18d"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "b4ca763ce00c58b962c61046ba1663d2a7c86feaef095baf1a0fef274d15c76f"
metafile = true

[[files]]
file = "mods/individual-keep-inventory.pw.toml"
hash = "67660a24e57eae12e2891d707a936ca2ec1a27d7263061ee5b7c8d4e0dc1ea7d"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "9d9819273bee47c7bc17cf159a1161a079f9d44c2bf314f4fbb232fc44b4fb34"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "165c73ae8776595fd868c13edf6fb85a05f39bf2f9cc46cf836c3909c5f67d20"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "3f7830571fca4510a7587d7dfe59efaa72050290f6c0b3b67f56ff84ad47547c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "721a565f85d7948e5638c0436bd128f073253eac0fc309bd83664bf143e0638b"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "ec178bfa73687fe31a6fbc24b6fdbabf4701c733b9e8dbeb837b0efb010c8443"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "ea21e37843db1efe11e577bae548f3c368473e73a4a304d91f01d4d157fabd06"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "548c56f04f1ec59d567a7bf7968951a5e0e53a0c66325d12fa5b8e60b4fa82c6"
metafile = true

[[files]]
file = "mods/log-ip-remover.pw.toml"
hash = "88f935d8a4e7d7d3881c3a21ac0922435ec2d3380fe900b9a290046f68dcf9fc"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "fe29a15ecb43d87c97671dd2f8c514a8ebf326893dde388e7e0de062a8a7b25b"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "67681c3ed65204913589978125582d7b146da717014aa28f5eef42e187fa99e5"
metafile = true

[[files]]
file = "mods/map-atlases.pw.toml"
hash = "57bb735e320eeec45faffb790fa42b3fa6bc440a9bd0db2463946351139e6252"
metafile = true

[[files]]
file = "mods/mcr_blahaj.pw.toml"
hash = "baeed1706de0e9c09a31c25c24344b0b051420330cca6d2b1eadcb0197b3a1c2"
metafile = true

[[files]]
file = "mods/mighty-mail-fabric.pw.toml"
hash = "3328115fa54c017c856917609c15e3eac99b297ebe26e4a1ea0591a118b2e22f"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "af4d8b79b9c54b3109158803ea44eea671bdfd018e158d86cee804180651e0dd"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "99f845b6b37ce93114632949525dc3f8f824a7dccf509cbd64f967a9e989d6b8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "16f66d1e8f13e95cd5b8e4c6ffd83c5d7c6f8afd0c1db9be81fe159a08d51f3e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "327839ffaf6df68f41f9bb25a462b546aa3565907b3556b861a9f21363eeefd9"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "116288b5626198547b9368b5bc3f76a2137e5e2187296ee58576c0980b14076f"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "90fad0aae5503bc1f85c9c56250888db28b2c047cfdea2776116c2d1061bdd20"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "a8481ceb044dbe3842121a0b345152953b2a554f8152ec56ca72c4e49b5a2159"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "1de9178faac8fd1593d9ed8bfbbcf74338566f6d6c7020266624989fcfcf077c"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "30ca74e8ad6bedc4d12fb3611bda27aa1e95812f533b4aeb2609504e154a585a"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "fb69980ffe21d2cc24b8d0359275a050333e9fa5ec9b00c16dfdb23ad9e2cd0f"
metafile = true

[[files]]
file = "mods/probejs.pw.toml"
hash = "efa262a087280f0b60873c10d5d82ead3bb4c22bbf685f7c1be3fed6e53e9f49"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "2fa3ae737139810017edfed3c1b09b8004ef3a49dbd9801186e7aeb62aabd2f1"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "a3754ed9ffecfd66cf09f87e2f652627e78f104bf2d1a34ca72e120023d27ff5"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "462dd81b6b1928bae07ee8c01fc8d0496285ad80f370565145722b087f7cca46"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "509d3d578afc6532245cadc22ed30776ec8b561308141467ebfe332190553952"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "385a545e40fc880fa9d39e07cc05b8b9efb25b1486ed07b135965f132d9343ae"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "6bd910a18e4d03580b5586e2e42ff190824c397f968d949e5c3cc2fd83183080"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "92aa4d3aa3ec76336d01ee22e9be70776238b733666962b33fddc733929d5d76"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "97d88dee115cee40c9a714c8ee0eefaad2418fda6087d3c8435c8f6002e8ddb7"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "5d92de7671329cbb34a358e4dfbc67382fa3f60b989b60f8d158668405657a20"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9e4e05853bc5636ecbc0a0c64b1c1037143e5a246067c4002b227e471a726783"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "820648f9b34fa6db0a70a6c87116265d33c90c86e98b6f3734a68aaa6c49466c"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
hash = "0771d0fdff0167314ec51dde072ec0a93e50c11752bb4a3f877aab4195fdf7c2"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "8c2b971dbe7bd4763c8904f468b3d959a675ce25d78b0f91450f03228a91ebc2"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "8f28fb29f87aefc847e0f1794b6ca7a71344f46a8311d8158b8d6997eee60a40"
metafile = true

[[files]]
file = "mods/textile_backup.pw.toml"
hash = "4dde4197c50cd04d1675de3478996b1515d44662080d505112628a5cfbde9ab7"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "caa75046b8d400e9e9459cbfe4f018be256c075fbf8c9f4c7c1a8b5c0525bc34"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "7a797ee3221d3cd8b8d8be5ca409cadd6a4e8216438a8908b1e275d672833b2f"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
hash = "47fe2c1dd998971b3d0ef65ae27c6ef54e2a0565285b4222f0620d2e4a587b35"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ab11927cd9e2079af34209947002a0f2bf3a2f4c8ec07abf7de73b4b4efee99a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "1bc58532964aa6d93ff8a1bdf7e7258b6ad68a9bf28b7173e0e2decb4dff2c95"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "4563ccf28f7b3bdc891bc9cd2b85294e0339a8c0f1b0a4388f74adb105813920"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "d561a943083b2f61b656f6bd99437679c62ee60932f90d346d9df36592249a2c"
metafile = true
