name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55c9a7476ea7b3b4a8258f77cf93c37ee672fe2ccf2d991a53b9ece5e67e30db"

[versions]
fabric = "0.15.4"
minecraft = "1.20.1"
