name = "SillyPack"
author = "SillyPack Authors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8ae9f8f4f599aecbc810b54513ab45896c3ded0d079c692a8a83a0190601209"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
